services:
  server:
    container_name: babbel-server
    image: babbel-server:latest
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgres://root_user:root-password@postgres:5432/babbeldb
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    depends_on:
      - redis
      - postgres
    command: pnpm start:dev

  redis:
    container_name: cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  postgres:
    container_name: babbel-database
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my-password
      POSTGRES_DB: babbeldb
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  redis:
    driver: local
  pgdata:
    driver: local
